//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class agent_info
    {
        public int id { get; set; }
        public int id_properties { get; set; }
        public string agent { get; set; }
        public int national_number { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string phone_number { get; set; }
        public string whatsapp_ink { get; set; }
    
        public virtual property property { get; set; }
    }
}
