//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_info
    {
        public int id { get; set; }
        public string ceo_name { get; set; }
        public string company_name { get; set; }
        public string comapny_location_link { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string phone_number { get; set; }
        public string facebook_link { get; set; }
        public string instagram_link { get; set; }
        public string twitter_link { get; set; }
        public string linkedin_link { get; set; }
        public string youtube_link { get; set; }
        public string comapny_video_link { get; set; }
    }
}
