//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class get_touch_user_info
    {
        public int id { get; set; }
        public string fname { get; set; }
        public string sname { get; set; }
        public string email { get; set; }
        public string phone_number { get; set; }
        public string supject { get; set; }
        public string message { get; set; }
    }
}
