//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class agent_info
{
    public agent_info()
    {
        this.properties = new HashSet<property>();
    }

    public int agent_id { get; set; }
    public string agent { get; set; }
    public int national_number { get; set; }
    public string address { get; set; }
    public string email { get; set; }
    public string phone_number { get; set; }
    public string whatsapp_ink { get; set; }

    public virtual ICollection<property> properties { get; set; }
}

public partial class category
{
    public category()
    {
        this.properties = new HashSet<property>();
    }

    public int category_id { get; set; }
    public string category_name { get; set; }

    public virtual ICollection<property> properties { get; set; }
}

public partial class company_info
{
    public int id { get; set; }
    public string ceo_name { get; set; }
    public string company_name { get; set; }
    public string comapny_location_link { get; set; }
    public string address { get; set; }
    public string email { get; set; }
    public string phone_number { get; set; }
    public string facebook_link { get; set; }
    public string instagram_link { get; set; }
    public string twitter_link { get; set; }
    public string linkedin_link { get; set; }
    public string youtube_link { get; set; }
    public string comapny_video_link { get; set; }
}

public partial class portal_users
{
    public int id { get; set; }
    public string login { get; set; }
    public string password { get; set; }
}

public partial class properties_info
{
    public int id { get; set; }
    public int id_properties { get; set; }
    public string images { get; set; }
    public string city { get; set; }
    public string address { get; set; }
    public string info_propertie { get; set; }
    public int year_built { get; set; }
    public int Bedrooms { get; set; }
    public int Bathrooms { get; set; }
    public int Area { get; set; }
    public int Floor { get; set; }
    public int Parking { get; set; }
    public decimal price { get; set; }
    public string currency { get; set; }
    public string Payment_method { get; set; }
    public string long_address { get; set; }
    public string building_type { get; set; }
    public string Display_type { get; set; }
    public string Furnishing { get; set; }
    public string publich_date { get; set; }
    public string map_link { get; set; }
    public string youtube_video_link { get; set; }

    public virtual property property { get; set; }
}

public partial class property
{
    public property()
    {
        this.properties_info = new HashSet<properties_info>();
    }

    public int id_properties { get; set; }
    public int category_id { get; set; }
    public string title { get; set; }
    public string image_path { get; set; }
    public string properties_type { get; set; }
    public string OrginatorID { get; set; }
    public int agent_id { get; set; }

    public virtual agent_info agent_info { get; set; }
    public virtual category category { get; set; }
    public virtual ICollection<properties_info> properties_info { get; set; }
}

public partial class user
{
    public int id { get; set; }
    public string user_name { get; set; }
    public string login { get; set; }
    public string password { get; set; }
    public Nullable<bool> isHRAdmin { get; set; }
}

public partial class V_AllProperties
{
    public int id { get; set; }
    public string properties_type { get; set; }
    public string category_name { get; set; }
    public string image_path { get; set; }
    public string title { get; set; }
    public string city { get; set; }
    public string address { get; set; }
    public string long_address { get; set; }
    public int id_properties { get; set; }
    public int year_built { get; set; }
    public int Floor { get; set; }
    public int Area { get; set; }
    public int Bedrooms { get; set; }
    public int Bathrooms { get; set; }
    public int Parking { get; set; }
    public string Parking_Available { get; set; }
    public string info_propertie { get; set; }
    public string images { get; set; }
    public string price { get; set; }
    public string Payment_method { get; set; }
    public string currency { get; set; }
    public string building_type { get; set; }
    public string Display_type { get; set; }
    public string Furnishing { get; set; }
    public string publich_date { get; set; }
    public string map_link { get; set; }
    public string youtube_video_link { get; set; }
    public string agent { get; set; }
    public string phone_number { get; set; }
    public string whatsapp_ink { get; set; }
}

public partial class V_TopOneProperties
{
    public int id { get; set; }
    public string properties_type { get; set; }
    public string category_name { get; set; }
    public string image_path { get; set; }
    public string title { get; set; }
    public string city { get; set; }
    public string address { get; set; }
    public string long_address { get; set; }
    public int id_properties { get; set; }
    public int year_built { get; set; }
    public int Floor { get; set; }
    public int Area { get; set; }
    public int Bedrooms { get; set; }
    public int Bathrooms { get; set; }
    public int Parking { get; set; }
    public string Parking_Available { get; set; }
    public string info_propertie { get; set; }
    public string images { get; set; }
    public string price { get; set; }
    public string Payment_method { get; set; }
    public string currency { get; set; }
    public string building_type { get; set; }
    public string Display_type { get; set; }
    public string Furnishing { get; set; }
    public string publich_date { get; set; }
    public string map_link { get; set; }
    public string youtube_video_link { get; set; }
    public string agent { get; set; }
    public string phone_number { get; set; }
    public string whatsapp_ink { get; set; }
}

public partial class VT_agent_info
{
    public int agent_id { get; set; }
    public string agent { get; set; }
    public int national_number { get; set; }
    public string address { get; set; }
    public string email { get; set; }
    public string phone_number { get; set; }
    public string whatsapp_ink { get; set; }
}

public partial class VT_Properties
{
    public int id_properties { get; set; }
    public int category_id { get; set; }
    public string title { get; set; }
    public string image_path { get; set; }
    public string properties_type { get; set; }
    public string OrginatorID { get; set; }
    public int agent_id { get; set; }
}

public partial class VT_properties_info
{
    public int id { get; set; }
    public int id_properties { get; set; }
    public string images { get; set; }
    public string city { get; set; }
    public string address { get; set; }
    public string info_propertie { get; set; }
    public int year_built { get; set; }
    public int Bedrooms { get; set; }
    public int Bathrooms { get; set; }
    public int Area { get; set; }
    public int Floor { get; set; }
    public int Parking { get; set; }
    public decimal price { get; set; }
    public string currency { get; set; }
    public string Payment_method { get; set; }
    public string long_address { get; set; }
    public string building_type { get; set; }
    public string Display_type { get; set; }
    public string Furnishing { get; set; }
    public string publich_date { get; set; }
    public string map_link { get; set; }
    public string youtube_video_link { get; set; }
}

public partial class SP_AllProperties_by_currency_Result
{
    public int id { get; set; }
    public string properties_type { get; set; }
    public string category_name { get; set; }
    public string image_path { get; set; }
    public string title { get; set; }
    public string city { get; set; }
    public string address { get; set; }
    public string long_address { get; set; }
    public int id_properties { get; set; }
    public int year_built { get; set; }
    public int Floor { get; set; }
    public int Area { get; set; }
    public int Bedrooms { get; set; }
    public int Bathrooms { get; set; }
    public int Parking { get; set; }
    public string Parking_Available { get; set; }
    public string info_propertie { get; set; }
    public string images { get; set; }
    public string price { get; set; }
    public string Payment_method { get; set; }
    public string currency { get; set; }
    public string building_type { get; set; }
    public string Display_type { get; set; }
    public string Furnishing { get; set; }
    public string publich_date { get; set; }
    public string map_link { get; set; }
    public string youtube_video_link { get; set; }
    public string agent { get; set; }
    public string phone_number { get; set; }
    public string whatsapp_ink { get; set; }
}

public partial class SP_Get_Properties_by_id_Result
{
    public int id { get; set; }
    public string properties_type { get; set; }
    public string category_name { get; set; }
    public string image_path { get; set; }
    public string title { get; set; }
    public string city { get; set; }
    public string address { get; set; }
    public string long_address { get; set; }
    public int id_properties { get; set; }
    public int year_built { get; set; }
    public int Floor { get; set; }
    public int Area { get; set; }
    public int Bedrooms { get; set; }
    public int Bathrooms { get; set; }
    public int Parking { get; set; }
    public string Parking_Available { get; set; }
    public string info_propertie { get; set; }
    public string images { get; set; }
    public string price { get; set; }
    public string Payment_method { get; set; }
    public string currency { get; set; }
    public string building_type { get; set; }
    public string Display_type { get; set; }
    public string Furnishing { get; set; }
    public string publich_date { get; set; }
    public string map_link { get; set; }
    public string youtube_video_link { get; set; }
    public string agent { get; set; }
    public string phone_number { get; set; }
    public string whatsapp_ink { get; set; }
}

public partial class SP_search_by_category_name_Result
{
    public int id { get; set; }
    public string properties_type { get; set; }
    public string category_name { get; set; }
    public string image_path { get; set; }
    public string title { get; set; }
    public string city { get; set; }
    public string address { get; set; }
    public string long_address { get; set; }
    public int id_properties { get; set; }
    public int year_built { get; set; }
    public int Floor { get; set; }
    public int Area { get; set; }
    public int Bedrooms { get; set; }
    public int Bathrooms { get; set; }
    public int Parking { get; set; }
    public string Parking_Available { get; set; }
    public string info_propertie { get; set; }
    public string images { get; set; }
    public string price { get; set; }
    public string Payment_method { get; set; }
    public string currency { get; set; }
    public string building_type { get; set; }
    public string Display_type { get; set; }
    public string Furnishing { get; set; }
    public string publich_date { get; set; }
    public string map_link { get; set; }
    public string youtube_video_link { get; set; }
    public string agent { get; set; }
    public string phone_number { get; set; }
    public string whatsapp_ink { get; set; }
}

public partial class SP_TopOneProperties_by_currency_Result
{
    public int id { get; set; }
    public string properties_type { get; set; }
    public string category_name { get; set; }
    public string image_path { get; set; }
    public string title { get; set; }
    public string city { get; set; }
    public string address { get; set; }
    public string long_address { get; set; }
    public int id_properties { get; set; }
    public int year_built { get; set; }
    public int Floor { get; set; }
    public int Area { get; set; }
    public int Bedrooms { get; set; }
    public int Bathrooms { get; set; }
    public int Parking { get; set; }
    public string Parking_Available { get; set; }
    public string info_propertie { get; set; }
    public string images { get; set; }
    public string price { get; set; }
    public string Payment_method { get; set; }
    public string currency { get; set; }
    public string building_type { get; set; }
    public string Display_type { get; set; }
    public string Furnishing { get; set; }
    public string publich_date { get; set; }
    public string map_link { get; set; }
    public string youtube_video_link { get; set; }
    public string agent { get; set; }
    public string phone_number { get; set; }
    public string whatsapp_ink { get; set; }
}
