//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace real_estate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class properties_info
    {
        public int id { get; set; }
        public int id_properties { get; set; }
        public string images { get; set; }
        public string city { get; set; }
        public string address { get; set; }
        public string info_propertie { get; set; }
        public int year_built { get; set; }
        public int Bedrooms { get; set; }
        public int Bathrooms { get; set; }
        public int Area { get; set; }
        public int Floor { get; set; }
        public int Parking { get; set; }
        public decimal price { get; set; }
        public string currency { get; set; }
        public string Payment_method { get; set; }
        public string long_address { get; set; }
        public string building_type { get; set; }
        public string Display_type { get; set; }
        public string Furnishing { get; set; }
        public string publich_date { get; set; }
        public string map_link { get; set; }
        public string youtube_video_link { get; set; }
    
        public virtual property property { get; set; }
    }
}
