//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace real_estate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_Properties
    {
        public int id_properties { get; set; }
        public int category_id { get; set; }
        public string title { get; set; }
        public string image_path { get; set; }
        public string properties_type { get; set; }
        public string OrginatorID { get; set; }
        public int agent_id { get; set; }
    }
}
